"""latest revisions

Revision ID: 8a8ddaac8fe8
Revises: d58e3b3b6f8f
Create Date: 2022-12-12 08:19:20.119087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8ddaac8fe8'
down_revision = 'd58e3b3b6f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_productuser_id', table_name='productuser')
    op.drop_table('productuser')
    op.drop_index('ix_product_id', table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='product_pkey')
    )
    op.create_index('ix_product_id', 'product', ['id'], unique=False)
    op.create_table('productuser',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='productuser_pkey')
    )
    op.create_index('ix_productuser_id', 'productuser', ['id'], unique=False)
    # ### end Alembic commands ###
